### ISSUE TITLE
Are you base 12 from Khan Academy? Please respond

### ISSUE THREAD

**Issue by SharkFinPro** [DozenalFTW/server2#2]
Hello? Please respond...

**Comment by DozenalFTW** [comment]
Not sure what you are talking about...

**Comment by SharkFinPro** [comment]
Khan Academy
This is your profile right?
https://www.khanacademy.org/profile/qindiandefence

**Comment by SharkFinPro** [comment]
(or at least your old username?)

**Comment by SharkFinPro** [comment]
Anti Cute Stuff? Please tell me base 12..

**Comment by DozenalFTW** [comment]
No, but I always found that guy interesting... especially the part about dozenal.
